version: "2.4"
services:
  # START PLEX
  plex:
    image: linuxserver/plex:latest
    network_mode: host
    environment:
      PUID: 1000
      PGID: 1000
      VERSION: 1.32.7.7621-871adbd44
      UMASK_SET: 022 #optional
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${VOLUMES_PATH}/plex/library:/config
      - ${MEDIA_PATH}/tv:/data/tvshows
      - ${MEDIA_PATH}/movies:/data/movies
      - ${MEDIA_PATH}/music:/data/music
      - ${MEDIA_PATH}/photos:/data/photos
      - ${VOLUMES_PATH}/plex/transcode:/transcode
    restart: unless-stopped
  # END PLEX
  # START OVERSEERR
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    environment:
      PUID: 1000
      PGID: 1000
      LOG_LEVEL: debug
      TZ: Eruope/Zurich
      VIRTUAL_HOST: overseerr.${TLD},ombi.${TLD}
      LETSENCRYPT_HOST: overseerr.${TLD},ombi.${TLD}
      VIRTUAL_PORT: 5055
    restart: unless-stopped
    volumes:
      - ${VOLUMES_PATH}/overseerr:/config
    depends_on:
      - radarr
      - sonarr
      - plex
    networks:
      - base-network
  # END OVERSEERR
  # START SONARR
  sonarr:
    image: linuxserver/sonarr:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Zurich
      VIRTUAL_HOST: sonarr.${TLD}
      LETSENCRYPT_HOST: sonarr.${TLD}
      VIRTUAL_PORT: 8989
    ports:
      - "8989:8989"
    volumes:
      - ${VOLUMES_PATH}/sonarr/:/config
      - ${MEDIA_PATH}/tv/:/tv
      - ${VOLUMES_PATH}/nzbget/downloads:/downloads
      - ${VOLUMES_PATH}/transmission/downloads:/downloads-transmission
    restart: unless-stopped
    depends_on:
      - nzbget
      - jackett
      - transmission
    networks:
      - base-network
  # END SONARR
  # START RADARR
  radarr:
    image: linuxserver/radarr:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Zurich
      VIRTUAL_HOST: radarr.${TLD}
      LETSENCRYPT_HOST: radarr.${TLD}
      VIRTUAL_PORT: 7878
    ports:
      - "7878:7878"
    volumes:
      - ${VOLUMES_PATH}/radarr/:/config
      - ${MEDIA_PATH}/movies/:/movies
      - ${VOLUMES_PATH}/nzbget/downloads:/downloads
      - ${VOLUMES_PATH}/transmission/downloads:/downloads-transmission
    restart: unless-stopped
    depends_on:
      - nzbget
      - jackett
      - transmission
    networks:
      - base-network
  # END RADARR
  # START BAZARR
  bazarr:
    image: linuxserver/bazarr:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Zurich
      VIRTUAL_HOST: bazarr.srv.ajil.ch
      LETSENCRYPT_HOST: bazarr.srv.ajil.ch
      PROXY_LOCATION: bazarr
      VIRTUAL_PORT: 6767
    volumes:
      - ${VOLUMES_PATH}/bazarr/config:/config
      - ${MEDIA_PATH}/movies:/movies
      - ${MEDIA_PATH}/tv:/tv
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
    networks:
      - base-network
  # END BAZARR
  # START NZBGet
  nzbget:
    image: linuxserver/nzbget:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Zurich
      VIRTUAL_HOST: nzbget.${TLD}
      LETSENCRYPT_HOST: nzbget.${TLD}
      VIRTUAL_PORT: 6789
    volumes:
      - ${VOLUMES_PATH}/nzbget/config:/config
      - ${VOLUMES_PATH}/nzbget/downloads:/downloads
    restart: unless-stopped
    networks:
      - base-network
  # END NZBGet
  # START TRANSMISSION+OPENVPN
  transmission:
    image: haugene/transmission-openvpn:latest
    environment:
      PUID: 1000
      PGID: 1000
      TRANSMISSION_WEB_UI: transmission-web-control
      CREATE_TUN_DEVICE: "true"
      OPENVPN_PROVIDER: PIA
      OPENVPN_CONFIG: switzerland
      OPENVPN_USERNAME: ${OPENVPN_USER}
      OPENVPN_PASSWORD: ${OPENVPN_PW}
      OPENVPN_OPTS: "--inactive 3600 --ping 10 --ping-exit 60"
      OVERRIDE_DNS_1: 8.8.8.8
      OVERRIDE_DNS_2: 8.8.4.4
      WEBPROXY_ENABLED: "false"
      TRANSMISSION_DOWNLOAD_DIR: /downloads-transmission/completed
      TRANSMISSION_INCOMPLETE_DIR: /downloads-transmission/incomplete
      LOCAL_NETWORK: 192.168.86.0/24
      TRANSMISSION_RATIO_LIMIT: 0.1
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_ALT_SPEED_DOWN: 0
      TRANSMISSION_ALT_SPEED_UP: 0
      TRANSMISSION_ALT_SPEED_TIME_ENABLED: "false"
      TRANSMISSION_ALT_SPEED_TIME_BEGIN: 540
      TRANSMISSION_ALT_SPEED_TIME_END: 1380
      TRANSMISSION_UTP_ENABLED: "false"
      TRANSMISSION_DOWNLOAD_QUEUE_ENABLED: "true"
      TRANSMISSION_DOWNLOAD_QUEUE_SIZE: 20
      VIRTUAL_HOST: transmission.${TLD}
      LETSENCRYPT_HOST: transmission.${TLD}
      VIRTUAL_PORT: 9091
    volumes:
      - ${VOLUMES_PATH}/transmission/config:/data
      - ${VOLUMES_PATH}/transmission/downloads:/downloads-transmission
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "31189:31189"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - base-network
  # END TRANSMISSION+OPENVPN
  # START JACKET
  jackett:
    image: linuxserver/jackett:latest
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Europe/Zurich
      VIRTUAL_HOST: jackett.${TLD}
      LETSENCRYPT_HOST: jackett.${TLD}
      VIRTUAL_PORT: 9117
    volumes:
      - ${VOLUMES_PATH}/jackett:/config
      - ${VOLUMES_PATH}/transmission/downloads:/downloads
    networks:
      - base-network
    restart: unless-stopped
  # END JACKET
  # BEGIN TDARR
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    # network_mode: bridge
    ports:
    #   - 8265:8265 # webUI port
      - 8266:8266 # server port
    cpuset: 0,1,2,3,4,5,6,7,8,9,10,11
    environment:
      TZ: Europe/London
      PUID: 1000
      PGID: 1000
      UMASK_SET: 002
      serverIP: 0.0.0.0
      serverPort: 8266
      webUIPort: 8265
      internalNode: true
      inContainer: true
      nodeName: transcoder
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
      VIRTUAL_HOST: tdarr.${TLD}
      LETSENCRYPT_HOST: tdarr.${TLD}
      VIRTUAL_PORT: 8265
    volumes:
      - ${VOLUMES_PATH}/tdarr/server:/app/server
      - ${VOLUMES_PATH}/tdarr/configs:/app/configs
      - ${VOLUMES_PATH}/tdarr/logs:/app/logs
      - ${MEDIA_PATH}:/media
      - ${VOLUMES_PATH}/tdarr/transcode_cache:/temp
      - /lib/firmware/i915/:/lib/firmware/i915/
    devices:
      - /dev/dri:/dev/dri
    networks:
      - base-network
  # END TDARR
networks:
  base-network:
    external: true
